Added module idrac_redfish_subscription
dell/dellemc-openmanage-ansible-modules pull request #258
Opened 2021-04-06 20:55 UTC by TrevorSquillario

This module allows you to create or delete Redfish Subscriptions for Metric Reports or Alerts.

Unit test included, code coverage=92%

Signed-off-by: Trevor Squillario <Trevor_Squillario@Dell.com>

2021-04-16 10:07 UTC, rajeevarakkal commented
Hello,

please check the issue reported by CI/CD above.. for example

```
ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/idrac_redfish_subscription.py:0:0: module-invalid-version-added: DOCUMENTATION: version_added ('2.9') is not a valid collection version (see specification at https://semver.org/): invalid semantic version '2.9'. Got {'module': 'idrac_redfish_subscription', 'short_description': 'Manage Redfish Subscriptions', 'version_added': '2.9', 'description': ['This module allows you to create or delete Redfish Subscriptions for Metric Reports or Alerts.', 'HTTPS is required for the destination listening server. An example of a listening server is the Logstash HTTP Input Plugin.', 'The maximum number of subscriptions a user can create is 2.'], 'options': {'baseuri': {'description': 'IP Address of the target out-of-ba...
```

2021-04-20 11:51 UTC, rajeevarakkal requested changes
@TrevorSquillario - please rename this module to 'redfish_event_subscription'

2021-04-20 13:09 UTC, TrevorSquillario commented
I'll work on these and resubmit.

2021-04-21 21:06 UTC, TrevorSquillario commented
All test passed except the `devel` ones. I don't think this is related to my code....

They errored out with `ModuleNotFoundError: No module named 'ansible.constants'`

2021-04-22 04:07 UTC, rajeevarakkal commented
> All test passed except the `devel` ones. I don't think this is related to my code....
> 
> They errored out with `ModuleNotFoundError: No module named 'ansible.constants'`

Thanks.

Yup, you are right, we are still figuring out.. mostly due to some ansible devel changes happening.

Will be sharing few more comments by couple of day.

2021-08-05 16:41 UTC, TrevorSquillario commented
Any updates on this?

2021-08-19 20:39 UTC, anupamaloke commented
> Any updates on this?

@TrevorSquillario, this is currently being planned for Sep monthly release.

2021-09-01 20:57 UTC, TrevorSquillario commented
Done.

2021-09-02 04:29 UTC, sachin-apa commented on plugins/modules/redfish_event_subscription.py
> +    extends_documentation_fragment:
@TrevorSquillario  this should be outside the **options:**

```
extends_documentation_fragment:
  - dellemc.openmanage.redfish_auth_options
options:
    destination:
        description:
          - A HTTPS URI to the destination where the events are sent.
          - HTTPS is required.
        type: str
        required: True
```

2021-09-02 04:33 UTC, sachin-apa commented
> Done.

@TrevorSquillario: sorry if we were not clear on the addition of extends_documentation_fragment before, please correct this part of the documentation i have added a review comment on the lines.

2021-09-02 04:33 UTC, TrevorSquillario commented
Fixed :)

2021-09-02 04:42 UTC, sachin-apa commented
> Fixed :)

Thanks @TrevorSquillario  for the quick resolution. All tests has passed.
This is currently planned for September month release, we will merge it accordingly.

2021-09-24 08:13 UTC, rajeevarakkal approved these changes

2021-09-24 08:14 UTC, sachin-apa approved these changes

2021-09-24 08:16 UTC, merged