266 idrac_network.py fails with `AttributeError: 'NoneType' object has no attribute 'iDRAC'`
dell/dellemc-openmanage-ansible-modules pull request #268
Opened 2021-04-16 16:21 UTC by grantcurell

README.md:
- Added TOC
- Based on user feedback took @anupamaloke 's answer and provided an explanation for the required shares along with how to easily handle the share
- Changed the header Playbooks to Sample Playbooks so user's would have a better idea of what was there

idrac_network.py:
- Added error handling such that if the share is not valid the module gracefully fails. Fixes #266
- Removed open_url from imports since it was unused

Signed-off-by: Grant Curell <grant_curell@dell.com>

2021-06-02 04:49 UTC, jagadeeshnv requested changes
@grantcurell 
Apologies for the delay. The content looks fine, but need these changes.
Please change the title to something like "Handling invalid share and unused imports cleanup" or whichever is more appropriate considering all the modules modified in this PR.
As a first set of comments.
1. The README.md changes can be a separated from this PR for now.
2.  Please update the content to the latest
3. We will review the message and get back on it

2021-06-10 05:02 UTC, jagadeeshnv commented
@grantcurell Please update the file _**tests/unit/plugins/modules/test_idrac_firmware.py**_, then the checks will pass.

2021-06-11 03:08 UTC, grantcurell commented
Apologies - I'll be traveling tomorrow. I'll take a look Monday and make the changes

2021-06-16 13:14 UTC, grantcurell commented
> @grantcurell
> Apologies for the delay. The content looks fine, but need these changes.
> Please change the title to something like "Handling invalid share and unused imports cleanup" or whichever is more appropriate considering all the modules modified in this PR.
> As a first set of comments.
> 
> 1. The README.md changes can be a separated from this PR for now.
> 2. Please update the content to the latest
> 3. We will review the message and get back on it
> 4. Please exclude ome and redfish modules from this PR and lets keep it to idrac only

I just want to make sure I understand correctly, the request is to delete the changes to all the files in the commit except idrac_network.py and *remove* the fixes for #194 and #160 and leave both of those tickets open?

2021-06-16 13:23 UTC, jagadeeshnv commented
@grantcurell 

- Please retain the changes to all iDRAC modules  - idrac_*
- Delete the README and ome_* modules from this PR.(Preferably move to a new PR)
- Change the message as below for the iDRAC modules
```
module.fail_json(msg="Unable to access the share. Ensure that the share name, "
                             "share mount, and share credentials provided are correct.")
```

2021-06-22 15:47 UTC, jagadeeshnv commented
@grantcurell Can you enable "Allow edits from maintainers.” so that we can update  `tests/unit/plugins/modules/test_idrac_firmware.py` for the checks to pass and the merge this PR

2021-06-24 06:33 UTC, jagadeeshnv approved these changes

2021-06-24 10:35 UTC, rajeevarakkal commented on plugins/modules/idrac_firmware.py
> +            if not upd_share.IsValid:
```suggestion
            if not upd_share.IsValid:
```

double entry

2021-06-24 10:53 UTC, jagadeeshnv submitted a review, later dismissed

2021-06-24 11:08 UTC, jagadeeshnv commented
@grantcurell 
`plugins/modules/idrac_firmware.py` had issues with indentation and duplicate if conditions and UT checks for this was failing as UT file was not committed. We tried to exclude idrac_firmware.py from the commit, Since our release activity is in progress today(6/24)

Can you please fix the issues or restore the idrac_firmware module without any changes so that checks will pass.
For your quick reference, PR #288 has the required changes.

2021-06-25 02:56 UTC, grantcurell commented
Apologies for not being more responsive. I took on a new project and am working pretty well at max capacity. I'll be out of town tomorrow but I'll take a look when I'm at the airport Monday

2021-06-25 04:59 UTC, rajeevarakkal approved these changes

2021-06-25 05:00 UTC, felixs88 approved these changes

2021-06-25 05:01 UTC, rajeevarakkal commented
> Apologies for not being more responsive. I took on a new project and am working pretty well at max capacity. I'll be out of town tomorrow but I'll take a look when I'm at the airport Monday

No problem,   since our release is due, we will merge now and we will push the necessary UT correction immediately

2021-06-25 05:02 UTC, merged