v8.6.0 changelog and README updated
dell/dellemc-openmanage-ansible-modules pull request #597
Opened 2023-12-20 09:37 UTC by jagadeeshnv

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

2023-12-20 09:40 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2023-12-21 04:11 UTC, rajshekarp87 requested changes

2023-12-21 04:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- Enhanced idrac_certificates to support `CUSTOMCERTIFICATE` and upload of SSL key.
```suggestion
- Enhanced idrac_certificates module and idrac_certificate role to support `CUSTOMCERTIFICATE` and `HTTPS` certificate import with SSL key.
```

2023-12-21 04:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_certificates - The module is enhanced to support import and export of `CUSTOMCERTIFICATE`.
```suggestion
- idrac_certificates module and idrac_certificate role - This is enhanced to support import and export of `CUSTOMCERTIFICATE`.
```

2023-12-21 04:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_certificates - The module and role are enhanced to support upload of SSL key along with `HTTPS` certificate.
```suggestion
- idrac_certificates - The module and role are enhanced to support import of `HTTPS` certificate with SSL key.
```

2023-12-21 04:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_certificates - The `email_address` is no longer a required parameter.
```suggestion
- idrac_certificates module and idrac_certificate role - The `email_address` has been made an optional parameter.
```

2023-12-21 04:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_certificates - The `email_address` is no longer a required parameter. (https://github.com/dell/dellemc-openmanage-ansible-modules/issues/582).
```suggestion
- idrac_certificates - The `email_address` has been made an optional parameter. (https://github.com/dell/dellemc-openmanage-ansible-modules/issues/582).
```

2023-12-21 09:26 UTC, rajshekarp87 approved these changes, later dismissed

2023-12-21 09:33 UTC, rajshekarp87 approved these changes

2023-12-21 09:36 UTC, rajshekarp87 submitted a review, later dismissed

2023-12-21 10:21 UTC, sachin-apa approved these changes

2023-12-21 10:26 UTC, rajshekarp87 approved these changes

2023-12-21 10:28 UTC, Kritika-Bhateja-03 approved these changes

2023-12-21 11:24 UTC, merged