Molecule fixes for idrac_certificate
dell/dellemc-openmanage-ansible-modules pull request #598
Opened 2023-12-21 14:50 UTC by ShivamSh3

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

2023-12-21 14:55 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2023-12-22 04:05 UTC, rajshekarp87 approved these changes, later dismissed

2024-01-03 13:21 UTC, rajshekarp87 requested changes

2024-01-03 13:21 UTC, rajshekarp87 commented on roles/idrac_certificate/molecule/generateCSR/converge.yml
>              - 192.198.2.1
Use FQDN instead of IP

2024-01-04 05:44 UTC, ShivamSh3 commented on roles/idrac_certificate/molecule/generateCSR/converge.yml
>              - 192.198.2.1
done

2024-01-09 06:55 UTC, ABHISHEK-SINHA10 commented on roles/idrac_certificate/molecule/CTC/converge.yml
> +          - ctc_cert_file.stat.exists
Good 👍 that you have added other assertion, normally I see only for msg.

2024-01-09 06:55 UTC, ABHISHEK-SINHA10 approved these changes

2024-01-22 06:28 UTC, rajshekarp87 approved these changes

2024-01-22 06:55 UTC, merged