Changelogs
dell/dellemc-openmanage-ansible-modules pull request #627
Opened 2024-02-12 08:13 UTC by Kritika-Bhateja-03

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

2024-02-12 08:15 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-02-13 12:11 UTC, rajshekarp87 requested changes

2024-02-13 12:11 UTC, rajshekarp87 commented on docs/ATTRIBUTION.md
> +OpenSource Licenses for Ansible Provider for OpenManage Enterprise
```suggestion
OpenSource Licenses for Dell OpenManage Ansible Modules
```

2024-02-13 12:11 UTC, rajshekarp87 commented on docs/ATTRIBUTION.md
> +OpenSource Licenses for Ansible Provider for OpenManage Enterprise
Also add an entry as "Attribution" under "Table of Contents" of README.md

2024-02-13 13:31 UTC, sachin-apa commented on README.md
Lets add badge to show the code coverage of collections branch
[![codecov](https://codecov.io/gh/dell/dellemc-openmanage-ansible-modules/branch/collections/graph/badge.svg)](https://app.codecov.io/gh/dell/dellemc-openmanage-ansible-modules)

2024-02-14 05:32 UTC, Kritika-Bhateja-03 commented on README.md
added

2024-02-20 13:11 UTC, rajshekarp87 requested changes

2024-02-20 13:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- Role ``idrac_user`` is added to manage local users for iDRAC.
```suggestion
- Role ``idrac_user`` is added to manage local users of iDRAC.
```

2024-02-20 13:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_user - This role is introduced to manage local users for iDRAC.
```suggestion
- idrac_user - This role is introduced to manage local users of iDRAC.
```

2024-02-20 13:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- idrac_diagnostics - Issue(285322) - This module doesn't support ExportePSADiagnosticsResult with SOCKS Proxy.
```suggestion
- idrac_diagnostics - Issue(285322) - This module doesn't support export of diagnostics file to HTTP and HTTPS share via SOCKS proxy.
```

2024-02-20 13:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- dellemc.openmanage.idrac_diagnostics - This module allows to to run and export diagnostics on iDRAC.
Add a line space

2024-02-20 13:11 UTC, rajshekarp87 commented on CHANGELOG.rst
> +v9.0.0
Update changelogs/changelog.yaml file

2024-02-21 04:26 UTC, sachin-apa approved these changes

2024-02-21 05:07 UTC, rajshekarp87 approved these changes

2024-02-21 05:38 UTC, sachin-apa approved these changes

2024-02-21 05:38 UTC, merged