Changelogs update
dell/dellemc-openmanage-ansible-modules pull request #641
Opened 2024-04-19 09:13 UTC by ShivamSh3

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

2024-04-19 09:15 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-04-19 11:04 UTC, sachin-apa submitted a review, later dismissed

2024-04-19 11:34 UTC, rajshekarp87 requested changes

2024-04-19 11:34 UTC, rajshekarp87 commented on CHANGELOG.rst
> +- dellemc.openmanage.idrac_reset - Resets the iDRAC to factory default settings.
Remove this

2024-04-19 12:04 UTC, rajshekarp87 requested changes

2024-04-19 12:04 UTC, rajshekarp87 commented on changelogs/changelog.yaml
> +        - idrac_reset is enhanced to reset the iDRAC to factory default settings.'
```suggestion
        - idrac_reset module is enhanced to support the reset operation'
```

2024-04-19 12:04 UTC, rajshekarp87 commented on changelogs/changelog.yaml
> +      release_summary: '- idrac_session module is added to allows the creation and deletion of sessions on iDRAC.
```suggestion
      release_summary: '- idrac_session module is added to manage iDRAC sessions.
```

2024-04-19 12:04 UTC, rajshekarp87 commented on changelogs/changelog.yaml
> +        - idrac_reset - This module is enhanced to reset the iDRAC to factory default settings.
```suggestion
        - idrac_reset - This module is enhanced to support the reset operation.
```

2024-04-22 10:14 UTC, sachin-apa approved these changes

2024-04-22 12:35 UTC, rajshekarp87 approved these changes

2024-04-22 12:47 UTC, ABHISHEK-SINHA10 approved these changes

2024-04-22 12:56 UTC, singh-lovepreet1 approved these changes

2024-04-23 03:04 UTC, merged