[Validation] - omevv_baseline_profile_info
dell/dellemc-openmanage-ansible-modules pull request #769
Opened 2024-11-18 05:08 UTC by ShivamSh3

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### OUTPUT

```paste below

```
##### ADDITIONAL INFORMATION

```paste below

```
# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

2024-11-18 05:10 UTC, ansible-collections-svc commented
Can one of the admins verify this patch?

2024-11-19 15:35 UTC, Kritika-Bhateja-03 requested changes

2024-11-19 15:35 UTC, Kritika-Bhateja-03 commented on tests/integration/targets/omevv_baseline_profile_info/tests/all_omevv_baseline_profile_info.yaml
> +    hostname is not defined or ome_username is not defined or ome_password
It should be vcenter_username is undefined or vcenter_password is undefined

2024-11-19 15:35 UTC, Kritika-Bhateja-03 commented on tests/integration/targets/omevv_baseline_profile_info/tests/all_omevv_baseline_profile_info.yaml
> +    hostname is not defined or ome_username is not defined or ome_password
Check in other files as well.

2024-11-20 08:15 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/all_omevv_baseline_profile_info.yaml
> +    hostname is not defined or ome_username is not defined or ome_password
done

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/__helper.yml
Change the file nae to _helper.yaml

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/__pre_req_create.yml
change the file name to _pre_req_create.yaml

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - invalid_hostname.msg == "<urlopen error [Errno -2]
Assertion is not correct. kindly check based on the latest changes

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +        vcenter_username: invalid
Add assertion

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - 'invalid_user.msg == "HTTP Error 401: 401" or
Assertion is not correct. kindly check based on the latest changes

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - 'invalid_vcenter_password.msg == "HTTP Error 401: 401" or
Assertion is not correct. kindly check based on the latest changes

2024-11-20 08:29 UTC, rajshekarp87 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - invalid_validate_certs_expected_msg in invalid_validate_certs.msg
Assert exact message

2024-11-20 09:08 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/__helper.yml
done

2024-11-20 09:08 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/__pre_req_create.yml
done

2024-11-20 09:08 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - invalid_hostname.msg == "<urlopen error [Errno -2]
checked, it is proper only

2024-11-20 09:08 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +        vcenter_username: invalid
checked, it is proper only

2024-11-20 09:08 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - 'invalid_user.msg == "HTTP Error 401: 401" or
checked, it is proper only

2024-11-20 09:09 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - invalid_validate_certs_expected_msg in invalid_validate_certs.msg
checked, it is proper only

2024-11-20 09:09 UTC, ShivamSh3 commented on tests/integration/targets/omevv_baseline_profile_info/tests/invalid.yaml
> +          - 'invalid_vcenter_password.msg == "HTTP Error 401: 401" or
checked, it is proper only

2024-11-20 13:50 UTC, ABHISHEK-SINHA10 commented
Re-run the negative test once after merging collections in your branch, invalid test cases value might differ after Saksham's change in rest_api.py

2024-11-21 05:05 UTC, Saksham-Nautiyal approved these changes

2024-11-21 10:11 UTC, Kritika-Bhateja-03 approved these changes

2024-11-21 10:36 UTC, rajshekarp87 approved these changes

2024-11-22 04:50 UTC, merged